### ISSUE TITLE
arg matches index out of bounds when using arg that doesnt take value

### ISSUE THREAD

**Issue by nikita-skobov** [nikita-skobov/interactive-term#1]
https://github.com/nikita-skobov/interactive-term/blob/504c4432085c83839b3a4e276e63a7c5bfb7538d/src/utils.rs#L70

If cli.yml contains:

```yml
args:
  - interactive:
      short: i
      long: interactive
      help: run interactively instead of as a script.
  - already-repo:
      help: is the CWD
      long: already-repo
      takes_value: true
      default_value: "false"
```

and the interactive option is present, it gets an index out of bound.
